// Env is generated by `wrangler types` in worker-configuration.d.ts.
// Extend it with secrets that wrangler can't auto-detect.
export interface AppEnv extends Env {
	ANTHROPIC_API_KEY: string;
	GITHUB_TOKEN: string;
	GITHUB_WEBHOOK_SECRET: string;
	TURBO_REMOTE_CACHE_URL: string;
	TURBO_REMOTE_CACHE_TEAM: string;
	TURBO_REMOTE_CACHE_TOKEN: string;
}
